测试开始啦！
测试报错
测试结束啦！
2019-12-11 17:37:47,331 - root - INFO - 测试开始啦！ - [logger.py:50]
2019-12-11 17:37:47,340 - root - ERROR - 测试报错 - [logger.py:51]
2019-12-11 17:37:47,340 - root - INFO - 测试结束啦！ - [logger.py:53]
2019-12-11 18:01:06,829 - case - INFO - 测试开始啦！ - [logger.py:56]
2019-12-11 18:01:06,829 - case - ERROR - 测试报错 - [logger.py:57]
2019-12-11 18:01:06,829 - case - INFO - 测试结束啦！ - [logger.py:59]
